periods:

  2000s:
    [5.5, 8.2, 11.0, 13.9, 15.2, 17.1, 19.7, 21.3, 23.2, 24.8]

  1990s:
    [5.5, 8.2, 11.0, 13.9, 15.2, 17.1, 19.7, 21.3, 23.2, 24.8]

  1980s:
    [14.5, 15.3, 16.2, 17.3, 18.3, 19.2, 20.4, 21.6, 22.9, 24.1]


indexes_options:
  ["U.S. 30 Day TBill TR","Russell 2000 TR","S&P 500 TR","LB LT Gvt/Credit TR","MSCI EAFE TR"]

risky_assets:
  ["Russell 2000 TR","S&P 500 TR","LB LT Gvt/Credit TR","MSCI EAFE TR"]

risk_free_asset:
  "U.S. 30 Day TBill TR"
  
weight:
  Alex:
    0.2
  Roberto:
    0.6
  Cathy:
    0.9
